---
- name: Ensure fleetd binary
  copy:
    src: '{{ fleet_build_bin_path }}/{{ fleet_fleet_binary_file_name }}'
    dest: '{{ fleet_install_path }}/{{ fleet_fleet_binary_file_name }}'
    mode: '{{ fleet_install_binary_mode }}'
    owner: '{{ fleet_install_binary_owner }}'
    group: '{{ fleet_install_binary_group }}'

- name: Ensure fleetctl binary
  copy:
    src: '{{ fleet_build_bin_path }}/{{ fleet_fleetctl_binary_file_name }}'
    dest: '{{ fleet_install_path }}/{{ fleet_fleetctl_binary_file_name }}'
    mode: '{{ fleet_install_binary_mode }}'
    owner: '{{ fleet_install_binary_owner }}'
    group: '{{ fleet_install_binary_group }}'