---
- name: Ensure target directory exists
  file:
    dest: '{{ fleet_target_directory }}'
    state: directory

- name: Checkout Git repo
  git:
    repo: '{{ fleet_git_repository }}'
    dest: '{{ fleet_target_directory }}'
    update: '{{ fleet_build_repo_update | default(false) }}'
    version: '{{ fleet_build_version | default(fleet_build_version_default) }}'
  register: fleet_git_result

- name: Check if binary is build already
  stat:
    path: '{{ fleet_fleet_binary_file }}'
  register: fleet_binary_file

- name: Build binaries
  shell: '{{ fleet_target_directory }}/build'
  args:
    chdir: '{{ fleet_target_directory }}'
  when: not fleet_binary_file.stat.exists or fleet_git_result.changed

- name: Ensure symlink to fleet binary
  file:
    src: '{{ fleet_fleet_binary_file }}'
    path: '{{ fleet_install_symlink_path }}/{{ fleet_fleet_binary_file_name }}'
    state: link
  when: fleet_install_create_symlink and '{{ ansible_system }}' == 'Linux'

- name: Ensure symlink to fleetctl binary
  file:
    src: '{{ fleet_fleetctl_binary_file }}'
    path: '{{ fleet_install_symlink_path }}/{{ fleet_fleetctl_binary_file_name }}'
    state: link
  when: fleet_install_create_symlink